

//AUT Action Types
export const LOGIN_USER = 'LOGIN_USER'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'
export const SET_ERRORS = "SET_ERRORS"
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER'



//CREDIT ACTION TYPES
export const ADD_CREDIT_CARD_SUCCESS = "ADD_CREDIT_CARD_SUCCESS"
export const ADD_CREDIT_CARD_FAIL = "ADD_CREDIT_CARD_FAIL"
export const LOAD_ALL_CREDIT_CARD = "LOAD_ALL_CREDIT_CARD"


//WALLET ACTION TYPES
export const GET_ALL_TRANSACTION = "GET_ALL_TRANSACTION"

